#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the mindMapper command anywhere in a user's
# workspace.

cmdScript=$(pwd)/.venv/bin/mindMapper

cat << CMD_SCRIPT > $HOME/.local/bin/mindMapper
#!/bin/sh

# This shell script was created by the mindMapper tool
#       './scripts/installEditableMindMapperCommand'
# script.

exec $cmdScript \$@
CMD_SCRIPT

chmod a+x $HOME/.local/bin/mindMapper

echo ""
echo "Editable mindMapper command has been created"
echo ""
